### ISSUE TITLE
Delete dotnet in KoreBuild break after the MSI installation

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/KoreBuild#67]
https://github.com/aspnet/KoreBuild/blob/dev/build/KoreBuild.ps1#L46 

That one fails after you install the MSI because you cannot delete from program files if you're in a console that's not elevated.

```
Remove-Item : Cannot remove item C:\Program
Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002426\dotnet.exe: Access to the path 'C:\Program
Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002426\dotnet.exe' is denied.
At D:\aspnet\options\.build\KoreBuild.ps1:46 char:71
+ ... m $sharedPath -Recurse *dotnet.exe) | %{ $_.FullName } | Remove-Item;
+                                                              ~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Program File...2426\dotnet.exe:FileInfo) [Remove-It
   em], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.Remo
   veItemCommand
```

**Comment by pakrym** [comment]
So, what do you propose to do?

**Comment by victorhurdugaci** [comment]
Handle the error or something

**Comment by pakrym** [comment]
Handle how? Ignore won't help, tests that do `dotnet *` won't work.

**Comment by pakrym** [comment]
This file should be deleted, you either need to give access to it or delete manually.

**Comment by muratg** [comment]
What's the work here?

**Comment by mikeharder** [comment]
KoreBuild should be completely side-by-side with the MSI version of DotNet CLI, and never touch files installed by the MSI version.

I think the bug here, is if `%LocalAppData\Microsoft\dotnet` is in the PATH _after_ `%ProgramFiles%\dotnet`, then KoreBuild.ps1 doesn't modify the PATH:

```
if (!($env:Path.Split(';') -icontains $dotnetLocalInstallFolder))
{
    Write-Host "Adding $dotnetLocalInstallFolder to PATH"
    $env:Path = "$newPath"
}
```

I think the fix is just to remove the `if` statement, to ensure '%LocalAppData%\Microsoft\dotnet` is always first in the PATH.

**Comment by Eilon** [comment]
@mikeharder , a gift for you.

**Comment by mikeharder** [comment]
Looking at the history of `KoreBuild.ps1`, I think we should keep the `if` statement, since it was added to fix other issues.

@pakrym: Can we just revert https://github.com/aspnet/KoreBuild/commit/3f4e43ed92b5b540b2da1511d15ce4b66e89e0c5?  I see that `shared\Microsoft.NETCore.App\1.0.0-rc3-002754` no longer contains a `dotnet.exe`, so maybe this workaround is no longer needed?

**Comment by pakrym** [comment]
@mikeharder: no, it's still there even in 2780.

**Comment by muratg** [comment]
@mikeharder still `2 - Working`? Or postpone to 1.0.1?

**Comment by mikeharder** [comment]
This hasn't come up in several months, so I recommend closing and reopening if it becomes an issue again.
