### ISSUE TITLE
Is git a viable tool to download and keep the .build dir in sync?

### ISSUE THREAD

**Issue by pranavkm** [aspnet/KoreBuild#72]
I'm not sure if this was discussed when initially porting KoreBuild to use the zip file? It might be much easier to keep it up to date (something people constantly have trouble with) if we just clone the repo rather than download it as a zip and expect it to be deleted before it is updated.

**Comment by pranavkm** [comment]
cc @victorhurdugaci \ @dougbu \ @natemcmaster

**Comment by victorhurdugaci** [comment]
We had this discussion before https://github.com/aspnet/KoreBuild/pull/1#discussion_r54188960

**Comment by pranavkm** [comment]
Could we complain if git isn't in the path (or if we cannot discover it in the usual locations)? Seems like a small price to pay to keep it updated.

**Comment by dougbu** [comment]
What problem does `git` solve that deleting the `.zip` file before downloading it does not?

**Comment by pranavkm** [comment]
Small incremental downloads versus downloading a zip file everytime?

**Comment by dougbu** [comment]
> incremental downloads

We're talking about a few small files. What's the underlying issue you're trying to fix?

**Comment by natemcmaster** [comment]
Renewing this conversation: now that KoreBuild is MSBuild-based, we could use NuGet packages to distribute the parts of KoreBuild that update. For example, we could put the majority of KoreBuild's targets into a nuget package. 

The one piece that remains tricky is determining which version of dotnet.exe and .NET Core runtime to install. Since we need dotnet.exe to run NuGet, it's hard to keep the version of dotnet.exe stored in a nuget package. Ideas?

**Comment by Eilon** [comment]
Closing because it isn't clear what isn't working well. Switching to NuGet might be nice, but the value isn't clear.
